---

apiVersion: v1
kind: Service
metadata:
  name: '{{ k8s_service }}'
  labels:
    app: '{{ k8s_app_label }}'
  namespace: '{{ k8s_namespace }}'
spec:
  type: ClusterIP
  selector:
    k8s-app: '{{ k8s_app_label }}'
  ports:
  - name: http
    port: 80
    targetPort: 8080

#EOF