---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: '{{ k8s_ingress }}'
  namespace: '{{ k8s_namespace }}'
spec:
  rules:
  - host: '{{ k8s_ingress_host }}'
    http:
      paths:
      - backend:
          serviceName: '{{ k8s_service }}'
          servicePort: 80
  tls:
    - hosts:
      - '{{ k8s_ingress_host }}'
      secretName: '{{ k8s_ingress_cert }}'
  
#EOF