apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: '{{ k8s_ingress_cert }}'
  namespace: '{{ k8s_namespace }}'
spec:
  secretName: '{{ k8s_ingress_cert }}'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '{{ k8s_ingress_host }}'
  dnsNames:
  - '{{ k8s_ingress_host }}'
  acme:
    config:
    - http01:
        ingress: '{{ k8s_ingress }}'
      domains:
      - '{{ k8s_ingress_host }}'
